config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'pairbnb/home', to: 'pairbnb#home'

get 'pairbnb/profile', to: 'pairbnb#profile'

get 'pairbnb/listing', to: 'pairbnb#listing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

# class UsersController < Clearance::UsersController
# end

app/controllers/pairbnb_controller.rb
class PairbnbController < ApplicationController

  def home

  end

  def profile

  end

  def listing

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairbnbGrp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= stylesheet_link_tag "app.scss" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pairbnb/home.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <i class="material-icons">room</i>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">About<span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a href="#">Sign Up</a>
                </li>
                <li>
                    <a href="#">Login</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<div class="jumbotron">
    <div class="container">
        <h1 class-"lead" style="font-weight: 300; font-size: 50px;">PairBnb Book unique experiences <br>and homes in 191+ countries</h1>
    </div>
</div>


<%= link_to 'Profile', pairbnb_profile_path %>
<%= link_to 'Listing', pairbnb_listing_path %>

app/views/pairbnb/listing.html.erb
<h1>This is my listing</h1>

<%= link_to 'Home', pairbnb_home_path %>

app/views/pairbnb/profile.html.erb
<h1>This is my profile</h1>

<%= link_to 'Home', pairbnb_home_path %>